### ISSUE TITLE
How to train Monolithic Baseline?

### ISSUE THREAD

**Issue by albzni** [Jiayuan-Gu/hab-mobile-manipulation#9]
Hi @Jiayuan-Gu. Thanks for sharing such a great project implementation!
I notice that in your paper you utilize Monolithic RL as the worst baseline comparison, may I ask how I can reproduce this baseline performance using your code (or how I can modify the contents of the config file)?

**Comment by Jiayuan-Gu** [comment]
Thank you for the interest in our work. I will try to update them in the next few weeks.

**Comment by albzni** [comment]
Hello @Jiayuan-Gu.

Thank you indeed for your prompt response. Your willingness to update the monolithic baseline codes is sincerely appreciated!

I wonder if you might share some insight into your timeframe for implementing these updates, without any intention to rush you. Having a rough idea when they might be available would be greatly beneficial for planning purposes.

Thank you once again for your time and aid!

**Comment by ChangFengPoLang** [comment]
I also want to know the answer to this question.

**Comment by Jiayuan-Gu** [comment]
Hi @albzni and @ChangFengPoLang 
Sorry for the late reply. I have uploaded the configs relevant to monolithic policies to the branch `mono`: <https://github.com/Jiayuan-Gu/hab-mobile-manipulation/tree/mono>. For the `SetTable` task, the monolithic policy can not handle the first stage (opening the drawer, picking the object), and thus I do not include later stages.
Please let me know if you have any question.

**Comment by albzni** [comment]
Oh, that's great! Thank you very much for your reply! I will try to train the mono policies as soon as possible. : )
